### ISSUE TITLE
Current state of this project

### ISSUE THREAD

**Issue by sallner** [infrae/Products.Formulator#1]
Hello @thefunny42,

A customer of ours is using this package and we might need to port it to Python 3 and Zope 4. We would like to contribute these changes to upstream and merge it in this repo. Would you consider to give me and/or @icemac the respective privileges here an on pypi? Or do you prefer a different way of dealing with updates?

Best, 
Steffen

**Comment by thefunny42** [comment]
Hello,

I gave you access to pypi, however I am no longer in the infrae organization so cannot change the access to the repositories that are there. I believe I can merge any pull request or make tags. If you ask @kitblake he could maybe help you there.

Cheers,

Sylvain,

**Comment by kitblake** [comment]
Hi Steffen and Michael, 

You both have invitations for repo access.

This Product has a long history, going back to early days of Zope! If need be you can contact the original author, @faassen. 

If you proceed with updating it please follow good practice, make branches, etc. As Sylvain said he would be the one to handle PRs and such (I'm not technical). 

Best,
kitblake

**Comment by icemac** [comment]
Thank you for the ability to work on this project.

**Comment by sallner** [comment]
@kitblake Thank you for granting us the rights to work on this package. We will follow the general guidelines used in the Zopefoundation ecosystem. Thanks also to @thefunny42 for being there to look at pull requests.
